name: my-project-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: make build
      - name: Coverage to Codeclimate
          uses: saymon-says/codeclimate-action@2
          env:
            CC_TEST_REPORTER_ID:
              ${{ secrets.CODECLIMATE_KEY }}: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco